---
kind: pipeline
type: docker
name: basic_pipeline

platform:
  os: linux
  arch: amd64

steps:
- name: builtin-compile-pipeline
  image: golang:1.19
  command:
  - go
  - build
  - -o
  - /var/flow/pipeline
  - ./demo/basic
  environment:
    CGO_ENABLED: 0
    GOARCH: amd64
    GOOS: linux
  volumes:
  - name: flow
    path: /var/flow

- name: basic_pipeline
  image: golang:1.20
  commands:
  - /var/flow/pipeline --pipeline="basic pipeline" --client cli --build-id=$DRONE_BUILD_NUMBER --state=file:///var/flow-state/state.json --log-level=debug --version=latest ./demo/basic
  volumes:
  - name: flow
    path: /var/flow
  - name: flow-state
    path: /var/flow-state
  depends_on:
  - builtin-compile-pipeline

volumes:
- name: flow
  temp: {}
- name: flow-state
  temp: {}
- name: docker_socket
  host:
    path: /var/run/docker.sock

trigger:
  branch:
  - main
  event:
  - branch
  - tag
  ref:
  - refs/tags/v*

...
